In [262]:
import pandas as pd
import numpy as np

df_permit = pd.read_csv('dataset/Building_Permits.csv')

df_permit = df_permit.drop(['Permit Number'],axis=1)
df_permit = df_permit.drop(['Block'],axis=1)
df_permit = df_permit.drop(['Lot'],axis=1)
df_permit = df_permit.drop(['Street Number'],axis=1)
df_permit = df_permit.drop(['Street Number Suffix'],axis=1)
df_permit = df_permit.drop(['Unit'],axis=1)
df_permit = df_permit.drop(['Unit Suffix'],axis=1)
df_permit = df_permit.drop(['Description'],axis=1)
df_permit = df_permit.drop(['Permit Expiration Date'],axis=1)
df_permit = df_permit.drop(['Estimated Cost'],axis=1)
df_permit = df_permit.drop(['Existing Use'],axis=1)
df_permit = df_permit.drop(['Existing Units'],axis=1)
df_permit = df_permit.drop(['Plansets'],axis=1)
df_permit = df_permit.drop(['Location'],axis=1)
df_permit = df_permit.drop(['Record ID'],axis=1)
df_permit = df_permit.drop(['Filed Date'],axis=1)

df_permit['Number of Existing Stories'] = df_permit['Number of Existing Stories'].fillna(0)
df_permit['Number of Proposed Stories'] = df_permit['Number of Proposed Stories'].fillna(0)
df_permit['Structural Notification'] = df_permit['Structural Notification'].fillna(0)
df_permit['Voluntary Soft-Story Retrofit'] = df_permit['Voluntary Soft-Story Retrofit'].fillna(0)
df_permit['Fire Only Permit'] = df_permit['Fire Only Permit'].fillna(0)
df_permit['TIDF Compliance'] = df_permit['TIDF Compliance'].fillna(0)
df_permit['Site Permit'] = df_permit['Site Permit'].fillna(0)
df_permit['Street Suffix'] = df_permit['Street Suffix'].fillna(0)
df_permit['Revised Cost'] = df_permit['Revised Cost'].fillna(np.nanmedian(df_permit['Revised Cost']))
df_permit['Proposed Units'] = df_permit['Proposed Units'].fillna(np.nanmedian(df_permit['Proposed Units']))
df_permit['Existing Construction Type'] = df_permit['Existing Construction Type'].fillna(0)
df_permit['Existing Construction Type Description'] = df_permit['Existing Construction Type Description'].fillna(0)
df_permit['Proposed Construction Type'] = df_permit['Proposed Construction Type'].fillna(0)
df_permit['Proposed Construction Type Description'] = df_permit['Proposed Construction Type Description'].fillna(0)
df_permit['Proposed Use'] = df_permit['Proposed Use'].fillna(0)

df_permit = df_permit.dropna(subset=['First Construction Document Date'])
df_permit = df_permit.dropna(subset=['Neighborhoods - Analysis Boundaries'])
df_permit = df_permit.dropna(subset=['Zipcode'])
df_permit = df_permit.dropna(subset=['Issued Date'])

In [263]:
df_permit.head()

,Permit Type,Permit Type Definition,Permit Creation Date,Street Name,Street Suffix,Current Status,Current Status Date,Issued Date,Completed Date,First Construction Document Date,...,Proposed Units,TIDF Compliance,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode
0,4,sign - erect,05/06/2015,Ellis,St,expired,12/21/2017,11/09/2015,NaN,11/09/2015,...,2.0,0,3.0,constr type 3,0.0,0,0,3.0,Tenderloin,94102.0
1,4,sign - erect,04/19/2016,Geary,St,issued,08/03/2017,08/03/2017,NaN,08/03/2017,...,2.0,0,3.0,constr type 3,0.0,0,0,3.0,Tenderloin,94102.0
3,8,otc alterations permit,11/07/2016,Pacific,Av,complete,07/24/2017,07/18/2017,07/24/2017,07/18/2017,...,1.0,0,5.0,wood frame (5),5.0,wood frame (5),0,3.0,Nob Hill,94109.0
4,6,demolitions,11/28/2016,Market,St,issued,12/01/2017,12/01/2017,NaN,11/20/2017,...,2.0,0,3.0,constr type 3,0.0,0,0,6.0,Tenderloin,94102.0
5,8,otc alterations permit,06/14/2017,Indiana,St,issued,07/06/2017,07/06/2017,NaN,07/06/2017,...,326.0,0,1.0,constr type 1,1.0,constr type 1,0,10.0,Potrero Hill,94107.0

In [264]:
df_date = df_permit[['Permit Creation Date','Current Status Date','Issued Date','Completed Date']]
df_date['Permit Creation Date'] = pd.to_datetime(df_date['Permit Creation Date'])
df_date['Current Status Date'] = pd.to_datetime(df_date['Current Status Date'])
df_date['Issued Date'] = pd.to_datetime(df_date['Issued Date'])
df_date['Completed Date'] = df_date['Completed Date'].fillna("12/12/2050")
df_date['Completed Date'] = pd.to_datetime(df_date['Completed Date'])
df_date

D:\Programme\Anaconda\envs\ialab\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

D:\Programme\Anaconda\envs\ialab\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
D:\Programme\Anaconda\envs\ialab\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
D:\Programme\Anaconda\envs\ialab\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
D:\Programme\Anaconda\envs\ialab\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

       Permit Creation Date Current Status Date Issued Date Completed Date
0                2015-05-06          2017-12-21  2015-11-09     2050-12-12
1                2016-04-19          2017-08-03  2017-08-03     2050-12-12
3                2016-11-07          2017-07-24  2017-07-18     2017-07-24
4                2016-11-28          2017-12-01  2017-12-01     2050-12-12
5                2017-06-14          2017-07-06  2017-07-06     2050-12-12
6                2017-06-30          2017-07-12  2017-06-30     2017-07-12
7                2017-06-30          2017-06-30  2017-06-30     2050-12-12
8                2017-07-05          2017-07-05  2017-07-05     2050-12-12
9                2017-07-06          2017-07-06  2017-07-06     2050-12-12
10               2017-07-06          2017-07-06  2017-07-06     2050-12-12
11               2017-07-07          2017-07-07  2017-07-07     2050-12-12
12               2017-07-10          2017-07-10  2017-07-10     2050-12-12
14               2017-07-26          2017-07-26  2017-07-26     2050-12-12
15               2017-07-27          2017-07-27  2017-07-27     2050-12-12
16               2017-07-27          2017-07-27  2017-07-27     2050-12-12
17               2017-07-27          2017-07-27  2017-07-27     2050-12-12
19               2017-07-28          2017-07-28  2017-07-28     2050-12-12
20               2017-07-31          2017-07-31  2017-07-31     2050-12-12
23               2017-08-07          2017-08-07  2017-08-07     2050-12-12
24               2017-08-08          2017-08-08  2017-08-08     2050-12-12
25               2017-08-16          2017-08-16  2017-08-16     2050-12-12
26               2017-08-18          2017-08-18  2017-08-18     2050-12-12
27               2017-08-21          2017-08-21  2017-08-21     2050-12-12
28               2017-08-21          2017-08-21  2017-08-21     2050-12-12
29               2017-08-22          2017-08-22  2017-08-22     2050-12-12
30               2017-08-23          2017-08-23  2017-08-23     2050-12-12
31               2017-08-23          2017-08-23  2017-08-23     2050-12-12
32               2017-08-23          2017-08-23  2017-08-23     2050-12-12
34               2017-08-25          2017-08-25  2017-08-25     2050-12-12
35               2017-08-25          2017-08-25  2017-08-25     2050-12-12
...                     ...                 ...         ...            ...
198835           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198837           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198840           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198841           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198842           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198843           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198844           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198845           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198846           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198847           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198850           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198851           2015-04-15          2018-02-23  2018-02-23     2050-12-12
198858           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198861           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198863           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198865           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198867           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198868           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198869           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198870           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198871           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198873           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198874           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198876           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198877           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198879           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198880           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198881           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198882           2018-02-23          2018-02-23  2018-02-23     2050-12-12
198883           2018-02-23          2018-02-23  2018-02-23     2050-12-12

[182263 rows x 4 columns]

In [265]:
df_date['Issued Date'] = (df_date['Issued Date'] - df_date['Permit Creation Date']).dt.days
df_date['Current Status Date'] = (df_date['Current Status Date'] - df_date['Permit Creation Date']).dt.days
df_date['Completed Date'] = (df_date['Completed Date'] - df_date['Permit Creation Date']).dt.days

df_date

D:\Programme\Anaconda\envs\ialab\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
D:\Programme\Anaconda\envs\ialab\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

D:\Programme\Anaconda\envs\ialab\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

       Permit Creation Date  Current Status Date  Issued Date  Completed Date
0                2015-05-06                  960          187           13004
1                2016-04-19                  471          471           12655
3                2016-11-07                  259          253             259
4                2016-11-28                  368          368           12432
5                2017-06-14                   22           22           12234
6                2017-06-30                   12            0              12
7                2017-06-30                    0            0           12218
8                2017-07-05                    0            0           12213
9                2017-07-06                    0            0           12212
10               2017-07-06                    0            0           12212
11               2017-07-07                    0            0           12211
12               2017-07-10                    0            0           12208
14               2017-07-26                    0            0           12192
15               2017-07-27                    0            0           12191
16               2017-07-27                    0            0           12191
17               2017-07-27                    0            0           12191
19               2017-07-28                    0            0           12190
20               2017-07-31                    0            0           12187
23               2017-08-07                    0            0           12180
24               2017-08-08                    0            0           12179
25               2017-08-16                    0            0           12171
26               2017-08-18                    0            0           12169
27               2017-08-21                    0            0           12166
28               2017-08-21                    0            0           12166
29               2017-08-22                    0            0           12165
30               2017-08-23                    0            0           12164
31               2017-08-23                    0            0           12164
32               2017-08-23                    0            0           12164
34               2017-08-25                    0            0           12162
35               2017-08-25                    0            0           12162
...                     ...                  ...          ...             ...
198835           2018-02-23                    0            0           11980
198837           2018-02-23                    0            0           11980
198840           2018-02-23                    0            0           11980
198841           2018-02-23                    0            0           11980
198842           2018-02-23                    0            0           11980
198843           2018-02-23                    0            0           11980
198844           2018-02-23                    0            0           11980
198845           2018-02-23                    0            0           11980
198846           2018-02-23                    0            0           11980
198847           2018-02-23                    0            0           11980
198850           2018-02-23                    0            0           11980
198851           2015-04-15                 1045         1045           13025
198858           2018-02-23                    0            0           11980
198861           2018-02-23                    0            0           11980
198863           2018-02-23                    0            0           11980
198865           2018-02-23                    0            0           11980
198867           2018-02-23                    0            0           11980
198868           2018-02-23                    0            0           11980
198869           2018-02-23                    0            0           11980
198870           2018-02-23                    0            0           11980
198871           2018-02-23                    0            0           11980
198873           2018-02-23                    0            0           11980
198874           2018-02-23                    0            0           11980
198876           2018-02-23                    0            0           11980
198877           2018-02-23                    0            0           11980
198879           2018-02-23                    0            0           11980
198880           2018-02-23                    0            0           11980
198881           2018-02-23                    0            0           11980
198882           2018-02-23                    0            0           11980
198883           2018-02-23                    0            0           11980

[182263 rows x 4 columns]

In [266]:
a = np.array(df_date['Completed Date'].values.tolist())
df_date['Completed Date'] = np.where(a > 5000, 9999, a).tolist()

D:\Programme\Anaconda\envs\ialab\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [280]:
df_permit['Current Status Date'] = df_date['Current Status Date']
df_permit['Issued Date'] = df_date['Issued Date']
df_permit['Completed Date'] = df_date['Completed Date']

In [281]:
df_permit.head()

,Permit Type,Permit Type Definition,Street Name,Street Suffix,Current Status,Current Status Date,Issued Date,Completed Date,First Construction Document Date,Structural Notification,...,Proposed Units,TIDF Compliance,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode
0,4,6,526,17,3,960,187,9999,11/09/2015,0,...,2.0,0,3.0,3,0.0,0,0,3.0,35,94102.0
1,4,6,636,17,5,471,471,9999,08/03/2017,0,...,2.0,0,3.0,3,0.0,0,0,3.0,35,94102.0
3,8,5,1176,2,2,259,253,259,07/18/2017,0,...,1.0,0,5.0,5,5.0,5,0,3.0,20,94109.0
4,6,1,994,17,5,368,368,9999,11/20/2017,0,...,2.0,0,3.0,3,0.0,0,0,6.0,35,94102.0
5,8,5,781,17,5,22,22,9999,07/06/2017,0,...,326.0,0,1.0,1,1.0,1,0,10.0,28,94107.0

In [282]:
#One hot encoder

from sklearn.preprocessing import LabelEncoder,OneHotEncoder

labelencoder_X_1 = LabelEncoder()

df_permit_encoded = df_permit
df_permit_encoded['Permit Type Definition'] =labelencoder_X_1.fit_transform(df_permit_encoded['Permit Type Definition'])
df_permit_encoded['Street Name'] =labelencoder_X_1.fit_transform(df_permit_encoded['Street Name'])
df_permit_encoded['Street Suffix'] =labelencoder_X_1.fit_transform(df_permit_encoded['Street Suffix'].astype(str))
df_permit_encoded['Current Status'] =labelencoder_X_1.fit_transform(df_permit_encoded['Current Status'].astype(str))
df_permit_encoded['Existing Construction Type Description'] =labelencoder_X_1.fit_transform(df_permit_encoded['Existing Construction Type Description'].astype(str))
df_permit_encoded['Structural Notification'] =labelencoder_X_1.fit_transform(df_permit_encoded['Structural Notification'].astype(str))
df_permit_encoded['TIDF Compliance'] =labelencoder_X_1.fit_transform(df_permit_encoded['TIDF Compliance'].astype(str))
df_permit_encoded['Site Permit'] =labelencoder_X_1.fit_transform(df_permit_encoded['Site Permit'].astype(str))
df_permit_encoded['Neighborhoods - Analysis Boundaries'] =labelencoder_X_1.fit_transform(df_permit_encoded['Neighborhoods - Analysis Boundaries'].astype(str))
df_permit_encoded['Proposed Construction Type Description'] =labelencoder_X_1.fit_transform(df_permit_encoded['Proposed Construction Type Description'].astype(str))
df_permit_encoded['Number of Proposed Stories'] =labelencoder_X_1.fit_transform(df_permit_encoded['Number of Proposed Stories'].astype(str))
df_permit_encoded['Voluntary Soft-Story Retrofit'] =labelencoder_X_1.fit_transform(df_permit_encoded['Voluntary Soft-Story Retrofit'].astype(str))
df_permit_encoded['Fire Only Permit'] =labelencoder_X_1.fit_transform(df_permit_encoded['Fire Only Permit'].astype(str))
df_permit_encoded['Revised Cost'] =labelencoder_X_1.fit_transform(df_permit_encoded['Revised Cost'].astype(str))
df_permit_encoded['Proposed Use'] =labelencoder_X_1.fit_transform(df_permit_encoded['Proposed Use'].astype(str))

In [283]:
df_permit_validated = df_permit.loc[df_permit['Site Permit'] == 1]
df_permit_refused = df_permit.loc[df_permit['Site Permit'] == 0]

In [284]:
df_permit_validated.shape

(3199, 26)

In [289]:
df_permit_encoded_equal = df_permit_validated.append(df_permit_refused.iloc[:3199,])
df_permit_encoded_equal.sample(frac=1)
df_permit_encoded_equal.head()

# df_permit_encoded_equal = df_permit.drop(['Permit Creation Date'],axis=1)
df_permit_encoded_equal = df_permit.drop(['First Constuction Document Date'],axis=1)

KeyError: "['First Constuction Document Date'] not found in axis"

In [288]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
np_scaled = min_max_scaler.fit_transform(df_permit_encoded_equal)
df_normalized = pd.DataFrame(np_scaled)

ValueError: could not convert string to float: '02/05/2013'

In [238]:
df_normalized.columns = df_permit_encoded_equal.columns
df_normalized['Site Permit'] = df_permit_encoded_equal['Site Permit']

In [240]:
df_normalized.head()

,Permit Type,Permit Type Definition,Street Name,Street Suffix,Current Status,Current Status Date,Issued Date,Completed Date,Structural Notification,Number of Existing Stories,...,Proposed Units,TIDF Compliance,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode
0,0.000000,0.428571,0.377897,0.333333,0.625,0.107420,0.111494,1.0,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.2,0.2,0.0,0.1,0.175,0.232143
1,0.285714,0.000000,0.815211,0.285714,0.250,0.421927,0.132759,1.0,1.0,0.033333,...,0.000667,0.0,1.0,1.0,1.0,1.0,0.0,0.6,0.825,0.446429
2,0.142857,0.571429,0.379679,0.190476,0.250,0.452381,0.092529,1.0,0.0,0.000000,...,0.000667,0.0,0.0,0.0,1.0,1.0,NaN,1.0,0.850,0.178571
3,0.285714,0.000000,0.295306,1.000000,0.250,0.545404,0.163218,1.0,1.0,0.033333,...,0.000667,0.0,1.0,1.0,1.0,1.0,0.0,0.7,0.350,0.517857
4,0.285714,0.000000,0.019014,0.190476,0.625,0.184385,0.191379,1.0,1.0,0.033333,...,0.000667,0.0,1.0,1.0,1.0,1.0,0.0,0.1,0.650,0.339286